### ISSUE TITLE
Transpiling imported modules

### ISSUE THREAD

**Issue by calcaide** [amwmedia/node-plop#6]
As the ava documentation says, [it can not transpile imported modules](https://github.com/avajs/ava#transpiling-imported-modules), but they suggest a workaround to achieve it.

**Comment by amwmedia** [comment]
sounds good to me, but I'm also wondering if it might be possible to just have each the the `tests/*.js` files renamed to `.ava.js` and run ava against them directly instead of using the index.ava.js. I think we would just need to `import` ava directly into each, so it would just be a minor change to the boilerplate.

This is my first project using `ava` for testing, so I'm sort of figuring this stuff out too.

**Comment by amwmedia** [comment]
never mind, I remember why I did it this way now. we need the `.before()` and `.after()` functions to run on the whole SET not just the individual test files because they all use the same directory.

I suppose we could set it up so that each one used it's own version of the `mock/src` folder. That might work nicely.

**Comment by calcaide** [comment]
Me too I discovered AVA here 😃 . I don't know if I understood well your first idea, but I guess, we can have each test like you said test/whatever.ava.js and run ava against them directly, just, in each test we have to set a .before() and .after() action.

Also your last comment could be a good idea too, if I understood well, you are saying something like `mock/src/abort-on-fail/` for abort-on-file.js, `mock/src/add-action-failure/` for add-action-failure.js and so on?

**Comment by calcaide** [comment]
I am spending some time to figure out how AVA works. I used to use Jasmine or Mocha for testing, and now I feel a bit strange with AVA. I am not saying that AVA doesn't like me or something like that, just that it feels weird to couldn't group a bunch of test like in Jasmine or Mocha  using a `describe()` but just I have to change my mind. I will take some time to think about a good approach, and I will ask you for your opinion.

**Comment by calcaide** [comment]
By the way, I have the workaround that they recommend in a branch, and it works perfectly, but now, with the thinks you comment I guess is better way to rethink about testing structure. I will work on this because I think I have some interesting. Hopefully, I will show you the approach tomorrow.

**Comment by amwmedia** [comment]
sounds good, I'll be interested to see what you come up with :-). 

The benefit to ava is that all of the tests can run in parallel. So it seems that having a different mock folder for each makes sense.
